name: CodeQuality

on:
  workflow_call:
    inputs:
      explicit_checks:
        required: false
        type: string

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10
      GEN: ninja

    steps:
      # Step 1: Checkout repository with submodules
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive  # Ensure submodules are initialized and fetched

      # Step 2: Install necessary packages
      - name: Install
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build clang-format-11 && sudo pip3 install cmake-format black cxxheaderparser pcpp

      # Step 3: List installed packages
      - name: List Installed Packages
        shell: bash
        run: pip3 freeze

      # Step 4: Run Format Check
      - name: Format Check
        shell: bash
        run: |
          make format-fix